apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: mern-eks
  region: us-east-1
  tags:
    project: sample-mern-microservices
managedNodeGroups:
  - name: app-workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 30
    privateNetworking: false
addons:
  - name: metrics-server
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
